# Generated by Django 6.0.1 on 2026-01-18 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField()),
                ("solution", models.TextField()),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("reference_link", models.URLField()),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="assessment.classification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Reference",
                "verbose_name_plural": "Classification References",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VulnAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.CharField(max_length=100)),
                ("ready", models.BooleanField(default=False)),
                ("tested_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vuln_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "ordering": ["-tested_on"],
            },
        ),
        migrations.CreateModel(
            name="FoundVulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vulnerability_type", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("info", models.TextField()),
                ("level", models.IntegerField()),
                ("parameter", models.CharField(max_length=255)),
                ("http_request", models.TextField()),
                ("curl_command", models.TextField()),
                ("found_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "classification",
                    models.ManyToManyField(blank=True, to="assessment.classification"),
                ),
                (
                    "vuln_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="assessment.vulnassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Found Vulnerability",
                "verbose_name_plural": "Found Vulnerabilities",
                "ordering": ["-found_on"],
            },
        ),
    ]
