# Generated by Django 6.0.1 on 2026-01-18 12:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("website", models.CharField(max_length=100)),
                ("ready", models.BooleanField(default=False)),
                ("tested_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "nuclei_results_file",
                    models.FileField(
                        blank=True, null=True, upload_to="nuclei_results/"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vuln_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "ordering": ["-tested_on"],
            },
        ),
    ]
