# Generated by Django 5.0.3 on 2024-03-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_classification_classificationreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
