# Generated by Django 5.0.3 on 2024-03-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_foundvulnerability_classification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vulnassessment",
            name="search_output",
        ),
    ]
