# Generated by Django 5.0.4 on 2024-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_remove_vulnassessment_search_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnassessment",
            name="ready",
            field=models.BooleanField(default=False),
        ),
    ]
